services:
  redis:
    image: redis
    ports:
      - 6379:6379
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
